name: geonet-tutorial
channels:
  - conda-forge
dependencies:
  - python[version='>=3.12']
  - cartopy
  - numpy
  - matplotlib[version='>=3.8']
  - pandas[version='>=2.2']
  - geopandas
  - gdal
  - obspy=[version='>=1.4']  
  - tabulate
  - ipykernel
